#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
This package contains modules related to the clustering problem.

This package must be used with "res" folder as working directory. See Path class for more details.
The classifier is powered by SciKit Learn SVM.

.. note: Scikit-learn: Machine Learning in Python, Pedregosa et al., JMLR 12, pp. 2825-2830, 2011.
.. warning: In order to use this package, one has to install scikit-learn library.

.. seealso: scikit-learn
"""
from os import getcwd


class SVCKernel:
	"""
	This class defines the names of the kernels that can be used in SVC.
	"""

	LINEAR = "linear"
	"""
	Linear kernel.
	"""

	POLY = "poly"
	"""
	Polynomial kernel.
	"""

	RBF = "rbf"
	"""
	Radial Basis Function (RBF) kernel
	"""

	SIGMOID = "sigmoid"
	"""
	Sigmoid kernel.
	"""

	PRECOMPUTED = "precomputed"
	"""
	Precomputed kernel.
	"""


class Path:
	"""
	This class defines path names used in clustering package.

	All these paths are define such that they are correct if the working directory is the "res" folder.
	"""

	@staticmethod
	def load(current_working_directory = None):
		if current_working_directory is None:
			current_working_directory = getcwd()

		Path.RES_PATH = current_working_directory
		Path.GENERATED_RES_PATH = '/'.join([Path.RES_PATH, "generated"])
		Path.R_GENERATED_RES_PATH = '/'.join([Path.GENERATED_RES_PATH, "R"])
		Path.CLUSTERING_MODULE_PATH = '/'.join([Path.RES_PATH, "../src/clustering"])
		Path.R_SCRIPT = '/'.join([Path.CLUSTERING_MODULE_PATH, "graph_descriptors.R"])
		Path.GENERATED_CSV_PATHS_FILE = '/'.join([Path.GENERATED_RES_PATH, "inputs.csv"])
		Path.GENERATED_XML_PATHS_FILE = '/'.join([Path.GENERATED_RES_PATH, "inputs.xml"])
		Path.DEFAULT_DATASET_SAMPLE_PATH = '/'.join([Path.RES_PATH, "clustering_dataset_sample"])
		Path.DEFAULT_SAMPLE_INPUTS_PATH = '/'.join([Path.DEFAULT_DATASET_SAMPLE_PATH, "inputs"])
		Path.DEFAULT_SAMPLE_RESULTS_PATH = '/'.join([Path.DEFAULT_DATASET_SAMPLE_PATH, "results"])

	RES_PATH = getcwd()
	"""
	Resources directory.
	"""

	GENERATED_RES_PATH = '/'.join([RES_PATH, "generated"])
	"""
	Directory containing resources generated by Python scripts.
	"""

	R_GENERATED_RES_PATH = '/'.join([GENERATED_RES_PATH, "R"])
	"""
	Directory containing resources generated by R scripts.
	"""

	CLUSTERING_MODULE_PATH = '/'.join([RES_PATH, "../src/clustering"])
	"""
	Path to clustering module, which contains scripts which must be used with RES_PATH as working directory.
	"""

	R_SCRIPT = '/'.join([CLUSTERING_MODULE_PATH, "graph_descriptors.R"])
	"""
	Script computing data to load in clustering_test module.
	"""

	CSV_EXT = ".csv"
	"""
	Pattern to use .csv files
	"""

	XML_EXT = ".xml"
	"""
	Pattern to use .csv files
	"""

	GRAPHML_EXT = ".graphml"
	"""
	Pattern to use .graphml files
	"""

	G_EXT = ".G"
	"""
	Pattern to use .G files
	"""

	NET_EXT = ".net"
	"""
	Pattern to use .net files
	"""

	TXT_EXT = ".txt"
	"""
	Pattern to use .txt files
	"""

	DEFAULT_EXT = GRAPHML_EXT
	"""
	Default pattern
	"""

	GENERATED_CSV_PATHS_FILE = '/'.join([GENERATED_RES_PATH, "inputs.csv"])
	"""
	Path of the CSV file containing the paths of the files which have to be used as input and results files in graph_descriptors.R.
	"""

	GENERATED_XML_PATHS_FILE = '/'.join([GENERATED_RES_PATH, "inputs.xml"])
	"""
	Path of the XML file containing the paths of the files which have to be used as input and results files in graph_descriptors.R.
	"""

	DEFAULT_DATASET_SAMPLE_PATH = '/'.join([RES_PATH, "clustering_dataset_sample"])
	"""
	Directory containing small dataset to test clustering module

	It is the default tests dataset for the project.
	"""

	DEFAULT_SAMPLE_INPUTS_PATH = '/'.join([DEFAULT_DATASET_SAMPLE_PATH, "inputs"])
	"""
	Directory containing full input dataset for clustering module
	"""

	DEFAULT_SAMPLE_RESULTS_PATH = '/'.join([DEFAULT_DATASET_SAMPLE_PATH, "results"])
	"""
	Directory containing all results for INPUTS_PATH files
	"""


class XMLKeys:
	ROOT = "root"
	"""
	Root element of XML files.
	"""

	DESCRIPTOR = "descriptor"
	"""
	Node defining a graph descriptor.
	"""

	PATH = "path"
	"""
	Node defining a path.
	"""

	TYPE = "type"
	"""
	Attribute defining the type of an element.
	"""

	VALUE = "value"
	"""
	Attribute defining the value of an element.
	"""

	INPUT_FILE = "input"
	"""
	Attribute defining the path to input train/test files.
	"""

	OUTPUT_FILE = "output"
	"""
	Attribute defining the path to output train/test files.
	"""

	RESULT_FILE = "results"
	"""
	Attribute defining the path to files that contain results computed by the R script.
	"""

	R_SCRIPT = "clustering_test.R"
	# R_SCRIPT = "../../src/clustering/graph_descriptors.R"
	"""
	Script computing graph descriptors to use with Classifier.
	"""
