#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
This package contains modules related to the clustering problem.

.. warning: In order to use this package, one has to install scikit-learn library.

.. seealso: scikit-learn
"""


class SVCKernel:
	"""
	This class defines the names of the kernels that can be used in SVC.
	"""

	LINEAR = "linear"
	"""
	Linear kernel.
	"""

	POLY = "poly"
	"""
	Polynomial kernel.
	"""

	RBF = "rbf"
	"""
	Radial Basis Function (RBF) kernel
	"""

	SIGMOID = "sigmoid"
	"""
	Sigmoid kernel.
	"""

	PRECOMPUTED = "precomputed"
	"""
	Precomputed kernel.
	"""


class Path:
	"""
	This class defines path names used in clustering package.
	"""

	R_GENERATED_RES_PATH = "../../res/generated/R/"
	"""
	Directory containing resources generated by R scripts.
	"""

	GENERATED_RES_PATH = "../../res/generated/"
	"""
	Directory containing resources generated by Python scripts.
	"""

	RES_PATH = "../../res/generated/"
	"""
	Resources directory.
	"""

	R_SCRIPT = "graph_descriptors.R"
	"""
	Script computing data to load in clustering_test module.
	"""
